# 监听IPV4的53端口
bind 0.0.0.0:53

# 完全禁用IPV6
force-AAAA-SOA yes

# 日志
log-level info
log-file /var/log/smartdns.log

# 缓存设置
# cache-size 32768
# cache-persist yes
cache-file /etc/smartdns/cache/file

# 配置上游服务器
server 100.100.2.136
server 100.100.2.138
# 配置AliceNetwork上游服务器组，并对上游使用-group进行分组
server 154.12.177.22 -group hk -exclude-default-group
server 157.20.104.47 -group sg -exclude-default-group

# ChatGPT DNS解锁
nameserver /browser-intake-datadoghq.com/hk
nameserver /chat.openai.com.cdn.cloudflare.net/hk
nameserver /gemini.google.com/hk
nameserver /openai-api.arkoselabs.com/hk
nameserver /openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net/hk
nameserver /openaicomproductionae4b.blob.core.windows.net/hk
nameserver /production-openaicom-storage.azureedge.net/hk
nameserver /static.cloudflareinsights.com/hk
nameserver /ai.com/hk
nameserver /algolia.net/hk
nameserver /api.statsig.com/hk
nameserver /auth0.com/hk
nameserver /chatgpt.com/hk
nameserver /chatgpt.livekit.cloud/hk
nameserver /client-api.arkoselabs.com/hk
nameserver /events.statsigapi.net/hk
nameserver /featuregates.org/hk
nameserver /host.livekit.cloud/hk
nameserver /identrust.com/hk
nameserver /intercom.io/hk
nameserver /intercomcdn.com/hk
nameserver /launchdarkly.com/hk
nameserver /oaistatic.com/hk
nameserver /oaiusercontent.com/hk
nameserver /observeit.net/hk
nameserver /openai.com/hk
nameserver /openaiapi-site.azureedge.net/hk
nameserver /openaicom.imgix.net/hk
nameserver /segment.io/hk
nameserver /sentry.io/hk
nameserver /stripe.com/hk
nameserver /turn.livekit.cloud/hk
