[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
dns-server = system
ipv6 = ture
prefer-ipv6 = false
dns-fallback-system = false
dns-direct-system = false
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = true
dns-direct-fallback-proxy = true

[Proxy Group]
Horizon = select, policy-regex-filter=oralce|Aliyun, select=0
Dukou = select, policy-regex-filter=^(oralce|Aliyun), select=0
OpenAI = select, policy-regex-filter=🇸🇬|新加坡|🇯🇵|日本, select=0

🍎 Apple = select, Horizon, Dukou
🇨🇳 Bing = select, Horizon, Dukou
💬 OpenAI = select, Horizon, OpenAI

[Rule]
RULE-SET, https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list, DIRECT
RULE-SET, https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list, DIRECT

RULE-SET, https://raw.gitmirror.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/China/China.list, DIRECT
RULE-SET, https://raw.gitmirror.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/China/China_Domain.list, DIRECT
RULE-SET, https://raw.gitmirror.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/ChinaMedia/ChinaMedia.list, DIRECT
RULE-SET, https://raw.gitmirror.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Apple/Apple.list, 🍎 Apple
RULE-SET, https://raw.gitmirror.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Apple/Apple_Domain.list, 🍎 Apple
RULE-SET, https://raw.gitmirror.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Bing/Bing.list, 🇨🇳 Bing
RULE-SET, https://raw.gitmirror.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/OpenAI/OpenAI.list, 💬 OpenAI

RULE-SET, https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list, REJECT
RULE-SET, https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list, REJECT

RULE-SET, https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list, DIRECT
RULE-SET, https://gaoyifan.github.io/china-operator-ip/china.txt, DIRECT
RULE-SET, https://gaoyifan.github.io/china-operator-ip/china6.txt, DIRECT

GEOIP, CN, DIRECT, no-resolve
FINAL, PROXY

[Host]
localhost = 127.0.0.1

[URL Rewrite]
^https?://(www.)?g.cn https://www.google.com 302
^https?://(www.)?google.cn https://www.google.com 302